const style = {
  mainContainer: {
    backgroundColor: 'linear-gradient(135deg, #0f0f0f, #1a1a1a)',
    maxWidth: "100%",
    margin: "auto",
    fontFamily: "'Inter',sans-serif !important",
    marginBottom: "30px",
  },
  mainsection: {
    padding: "0px 15px",
    maxWidth: "1280px !important",
    minHeight: "100vh !important",
    margin: "auto !important",
    fontFamily: "'Inter',sans-serif !important",
    position: "relative !important",
    display: "flex !important",
    justifyContent: "space-between !important",
    alignItems: "start !important",
    flexDirection: "row-reverse",
    "@media(max-width:767px)": {
      flexWrap: "wrap",
      justifyContent: "center",
      padding: "20px 0px",
      padding: "10px 15px",
    },
  },
  leftPanel: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "500px",
    margin: "0 15px 20px",
    padding: "30px 0 0",
    overflow: "hidden",
    backgroundColor: "custom.returnCalculatorBg",
    borderRadius: "10px",
    "@media(max-width:480px)": {
      display: "none",
      maxWidth: "100%",
    },
    "& h1": {
      fontSize: "26px",
      fontWeight: "600",
      width: "100%",
      textAlign: "center",
      color: "custom.white",
    },
  },
  imageSection: {
    position: "relative",
    display: "flex",
    width: "100%",
    marginTop: "35px",
    flexDirection: "row-reverse",
    justifyContent: "center",
    "@media(max-width:480px)": {
      flexWrap: "wrap",
    },
  },
  ImageContainer: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "300px",
    padding: "0 15px",
    "& img": {
      width: "100%",
      height: "auto",
      ObjectFit: "cover",
    },
    "& video": {
      width: "100%",
      height: "440px",
      height: "auto",
      ObjectFit: "cover",
    },
    "@media(max-width:480px)": {
      maxWidth: "100%",
      marginBottom: "40px",
    },
  },
  confirmQuantity: {
    position: "relative",
    fontWeight: "600",
    fontSize: "12px",
    border: "1px solid #fff",
    lineHeight: "28px",
    borderRadius: "16px",
    marginTop: "3px",
    height: "30px",
    color: "custom.white",
    textTransform: "capitalize",
  },
  confirmQuantityColour: {
    position: "relative",
    fontWeight: "600",

    background: "linear-gradient(90deg,#E14084,#3454FA,#54B5BB)",
    fontSize: "12px",
    lineHeight: "28px",
    borderRadius: "16px",
    alignItems: "center",
    marginTop: "3px",
    height: "30px",
    color: "custom.white",
    textTransform: "capitalize",
  },

  thumbnailContainer: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "141px",
    // height:"177px",
    margin: "0 25px",
    objectFit: "contain",
    maxHeight: "530px",
    // overflowY: "scroll",
    "& img": {
      width: "100px",
      marginBottom: "30px",
    },
    "& video": {
      width: "100%",
      marginBottom: "30px",
    },
    "& li.active": {
      opacity: "1",
      "& img": {
        border: "3px solid #FFFFFF",
      },
    },
    "@media(max-width:767px)": {
      maxWidth: "100%",
      display: "flex",
      justifyContent: "center",
    },
  },
  PriceSection: {
    position: "relative",
    display: "flex",
    padding: "30px",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    background: "#fff",
    marginTop: "25px",
    "& h3": {
      color: "#000",
      fontWeight: "700",
      fontSize: "24px",
    },
  },
  rightPanel: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "705px",
    padding: "10px 15px 0",
    overflow: "hidden",
    backgroundColor: "custom.primaryWatchBg",
    borderRadius: "10px",
    border: "1px solid #2F2C3C",
    // maxHeight: "890px",
    minHeight: "658px",
    color: "custom.white",
    "& h1": {
      fontSize: "28px",
      fontWeight: "600",
      width: "100%",
      textAlign: "center",
      color: "custom.white",
    },
    "& h4": {
      fontSize: "16px",
      fontWeight: "600",
      width: "100%",
      lineHeight: "20px",
      textAlign: "left",
      color: "custom.white",
    },
    "@media(max-width:480px)": {
      height: "auto",
      paddingTop: "10px",
      marginBottom: "50px",
    },
  },
  separatorLine1: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "610px",
    borderTop: "1px solid rgba(255, 255, 255, 0.3)",
    margin: "0 auto 10px",
  },
  separatorLine2: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "610px",
    borderTop: "1px solid rgba(255, 255, 255, 0.3)",
    margin: "10px auto",
  },
  quantityStyle: {
    color: "custom.white",
    "& span": {
      fontSize: "12px",
    },
  },
  separatorLine3: {
    position: "relative",
    display: "block",
    width: "100% !important",
    // maxWidth: "610px",
    borderTop: "1px solid rgba(255, 255, 255, 0.3)",
    // margin: "20px auto 40px",
  },
  description: {
    fontSize: "20px",
    fontWeight: "400",
    color: "custom.white",
    width: "100%",
    textAlign: "center",
    marginTop: "24px",
  },
  walletBalance: {
    position: "relative",
    display: "flex",
    justifyContent: "center ",
    margin: "auto",
    paddingTop: "10px",
    width: "100%",
    // maxWidth: "238px",
    color: "custom.white",
    fontSize: "16px",
    alignItems: "center",
    fontWeight: "400",
    "& img:first-child": {
      mixBlendMode: "exclusion",
    },
    "@media(max-width:480px)": {
      fontSize: "14px",
    },
  },
  tableData: {
    width: "100%",
    maxWidth: "608px",
    margin: "auto",
    fontSize: "16px",
    "& td": {
      border: "none",
      color: "custom.white",
      fontFamily: "Inter",
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "16px",

      paddingInline: "0px !important",
      "@media(max-width:480px)": {
        fontSize: "14px",
      },
    },
    "& th": {
      border: "none",
      padding: "10px 0",
      color: "custom.white",
      fontWeight: "400",
      fontSize: "16px",
      "@media(max-width:480px)": {
        fontSize: "14px",
      },
    },
  },

  reedemTableData: {
    width: "100%",
    margin: "auto",
    fontSize: "16px",
    background: "black",
    "& td": {
      border: "none",
      padding: "16px 0",
      color: "custom.white",
    },
    "& th": {
      border: "none",
      padding: "16px 0",
      paddingLeft: "27px",
      paddingRight: "27px",
      color: "custom.white",
      fontWeight: "700",
    },
  },

  buttonContainer: {
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "10px auto 24px",
    width: "100%",
    maxWidth: "608px",
  },
  btnAddAmount: {
    position: "relative",
    textAlign: "center",
    display: "block",
    fontWeight: "600",
    fontSize: "16px",
    margin: "0 5px",
    width: "100%",
    maxWidth: "614px",
    background: "linear-gradient(90deg,#E14084,#3454FA,#54B5BB)",
    borderRadius: "16px",
    height: "56px",
    color: "custom.white",
    textDecoration: "none",
    textTransform: "capitalize",
    "&:hover": {
      color: "#fff",
      textDecoration: "none",
    },
  },
  btnConfirm: {
    position: "relative",
    textAlign: "center",
    display: "block",
    fontWeight: "600",
    fontSize: "16px",
    width: "100%",
    maxWidth: "614px",
    background: "linear-gradient(90deg,#E14084,#3454FA,#54B5BB)",
    borderRadius: "10px",
    height: "56px",
    color: "white",
    textDecoration: "none",
    textTransform: "capitalize",
    "&:hover": {
      color: "#fff",
      textDecoration: "none",
    },
  },

  btnSkip: {
    position: "relative",
    textAlign: "center",
    display: "block",
    fontWeight: "600",
    width: "100%",
    fontSize: "16px",
    margin: "0 5px",
    maxWidth: "212px",
    border: "1px solid #fff",
    borderRadius: "16px",
    lineHeight: "1.24",
    height: "56px",
    color: "#fff",
    textTransform: "capitalize",
  },
  orderTypeContainer: {
    maxWidth: "608px",
    margin: "auto",
  },
  orderType: {
    position: "relative",
    fontWeight: "400",
    fontSize: "14px",
    background: "#2F2D3C",
    border: "1px solid #3D3A51",
    lineHeight: "20px",
    borderRadius: "4px",
    padding: "6px 40px",
    color: "#fff",
    textTransform: "capitalize",
    "&:hover": {
      background: "#2F2D3C",
    },
  },
  orderTypeColor: {
    background: "linear-gradient(90deg, #B238F6 5.83%, #E94278 92.92%);",
    "&:hover": {
      background: "linear-gradient(90deg, #B238F6 5.83%, #E94278 92.92%);",
    },
  },
  note: {
    fontSize: "12px",
    fontWeight: "400",
    color: "#ccc",
    width: "100%",
    maxWidth: "608px",
    margin: "0 auto 146px",
  },
  modalBtnContainer: {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    gap: "10px",
  },
  modalContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "100%",
    maxWidth: "465px",
    background: "#fff",
    borderRadius: "8px",
    padding: "36px",
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    "& h4": {
      fontSize: "20px",
      fontWeight: "600",
      color: "#000",
      width: "100%",
      textAlign: "center",
      marginBottom: "8px",
    },
    "& p": {
      fontSize: "14px",
      fontWeight: "400",
      color: "#000",
      width: "100%",
      textAlign: "center",
      marginBottom: "24px",
    },
    "& img": {
      textAlign: "center",
      // marginBottom:"24px"
    },
    "@media(max-width:480px)": {
      left: "10px",
      right: "10px",
      transform: "none",
    },
    width: "auto",
  },
  modalContainerSlippage: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "100%",
    maxWidth: "465px",
    background: "#242033",
    borderRadius: "8px",
    padding: "36px",
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    "& h4": {
      fontSize: "20px",
      fontWeight: "600",
      color: "custom.white",
      width: "100%",
      textAlign: "center",
      marginBottom: "8px",
    },
    "& p": {
      fontSize: "14px",
      fontWeight: "400",
      color: "custom.white",
      width: "100%",
      textAlign: "center",
      marginBottom: "24px",
    },
    "& img": {
      textAlign: "center",
      // marginBottom:"24px"
    },
    "@media(max-width:480px)": {
      left: "10px",
      right: "10px",
      transform: "none",
    },
    width: "auto",
  },
  btnConfirmSkip: {
    position: "relative",
    textAlign: "center",
    display: "block",
    fontWeight: "600",
    width: "100%",
    maxWidth: "180px",
    border: "1px solid #4f4f4f",
    borderRadius: "8px",
    height: "50px",
    color: "#4f4f4f",
    textTransform: "capitalize",
  },
  btnAddMoney: {
    position: "relative",
    textAlign: "center",
    display: "block",
    fontWeight: "600",
    width: "100%",
    // maxWidth: "180px",
    border: "solid",
    borderColor: "custom.marketPlaceBuyBorder",
    borderWidth: "thin",
    lineHeight: 1.25,
    borderRadius: "100px",
    height: "50px",
    color: "custom.white",

    textTransform: "capitalize",
  },
  btnReserveNFT: {
    position: "relative",
    textAlign: "center",
    display: "block",
    fontWeight: "600",
    width: "100%",
    background: "linear-gradient(90deg,#E14084,#3454FA,#54B5BB)",
    borderRadius: "100px",
    height: "50px",
    color: "#fff",
    textDecoration: "none",
    textTransform: "capitalize",
    "&:hover": {
      color: "#fff",
      textDecoration: "none",
    },
  },
  btnClose: {
    position: "absolute",
    display: "inline-block",
    top: "10px",
    right: "10px",
    cursor: "pointer",
  },

  /*=========PaymentSuccess========*/
  mainSucessSection: {
    padding: "60px 15px",
    maxWidth: "1280px",
    minHeight: "100vh",
    margin: "auto",
    fontFamily: "'Inter',sans-serif !important",
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    "@media(max-width:767px)": {
      flexWrap: "wrap",
      justifyContent: "center",
    },
  },
  leftSuccessPanel: {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "70%",
    maxWidth: "300px",
    ObjectFit: "conatin",
    margin: "0 15px 20px",
    "@media(max-width:480px)": {
      maxWidth: "60%",
    },
  },
  rightSuccessPanel: {
    position: "relative",
    display: "block",
    textAlign: "center",
    width: "100%",
    maxWidth: "705px",
    margin: "0 15px",
    padding: "30px 15px 0",
    overflow: "hidden",
    backgroundColor: "#242033",
    borderRadius: "10px",
    "& h1": {
      fontSize: "28px",
      fontWeight: "600",
      width: "100%",
      textAlign: "center",
      color: "#fff",
    },
  },
  successMessage: {
    fontSize: "18px",
    fontWeight: "400",
    color: "#FFFFFF !important",
    width: "100%",
    maxWidth: "608px",
    margin: "7px auto 0",
  },
  successSeparator: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "610px",
    borderTop: "1px solid rgba(255, 255, 255, 0.3)",
    margin: "20px auto",
  },
  successDescription: {
    fontSize: "16px",
    fontWeight: "400",
    color: "#FFFFFF !important",
    width: "100%",
    maxWidth: "477px",
    textAlign: "center",
    margin: "auto",
  },
  buttonSuccessContainer: {
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "50px auto 40px",
    width: "100%",
    maxWidth: "608px",
  },
  buttonRetryContainer: {
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "50px auto 40px",
    // marginLeft: "19%",
    width: "100%",
    maxWidth: "450px",
  },
  minusbtokenbtn: {
    display: "flex",
    width: "25px",
    minWidth: "25px !important",
    height: "25px",
    borderRadius: "50%",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: 600,
    paddingTop: " 0px",
    fontSize: "20px",
    color: "#E14084",
    marginLeft: "15px",
    "&:focus": {
      outline: 0,
    },
  },
  addbtokenbtn: {
    display: "flex",
    width: "25px",
    minWidth: "25px !important",
    height: "25px",
    justifyContent: "center",
    alignItems: "center",
    border: "none",
    // border: "1px solid #E14084",
    color: "#E14084",
    fontSize: "20px",
    paddingTop: " 0px",
    fontWeight: 600,
    "&:focus": {
      outline: 0,
    },
  },

  tokenBtn: {
    float: "right",
    position: "relative",
    display: "flex",
    justifyContent: "end",
    background: "#FFFFFF",
    border: "1px solid #E14084",
    borderRadius: "4px",
    width: "60px",
  },
  tokenBtnPrice: {
    float: "right",
    position: "relative",
    display: "flex",
    justifyContent: "end",
    paddingLeft: "30px",

    // background: "#FFFFFF",
    // border: "1px solid #E14084",
    // borderRadius: "4px",
    // width: "60px",
  },

  redeemCoinInput: {
    background: "#FFFFFF",
    // border: "1px solid #E14084",
    borderRadius: "16px",
    marginTop: "3px",
    color: "custom.white",
    width: "100px",
    textAlign: "center",
    fontWeight: 600,
    // marginRight: "15px",
    "&:focus-visible": {
      outline: "none",
    },
    "& .MuiInput-root": {
      "&:before, :after, :hover:not(.Mui-disabled):before": {
        borderBottom: 0,
      },
    },
  },

  Inter16Normal: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "16px",
    color: "custom.white",
    padding: "0px !important",
    // "@media(max-width:480px)": {
    //   maxWidth: "120px",
    //   marginLeft: "20px",
    //   fontSize: "14px",
    // },
  },
  errContainer: {
    background: "rgba(220, 160, 72, 0.1)",
    borderRadius: "12px",
    padding: "10px",
    width: "100%",
    maxWidth: "608px",
    margin: "auto",
    display: "flex",
    marginBottom: "10px",
    "& p": {
      color: "#E5392E",
      textDecoration: "none",
      fontWeight: "400",
      fontSize: "12px",
      paddingLeft: "5px",
    },
  },
  bottomErrContainer: {
    background: "rgba(220, 160, 72, 0.1)",
    borderRadius: "12px",
    padding: "10px",
    display: "flex",
    margin: "auto",
    marginBottom: "20px",
    // maxWidth: "80%",
    "& p": {
      color: "#DCA048",
      textDecoration: "none",
      fontWeight: "400",
      fontSize: "12px",
    },
  },
  Inter16Bold: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "16px",
    color: "custom.white",
  },

  tnc: {
    color: "#FFF",
    display: "flex",
    "& p": {
      paddingLeft: "5px",
      color: "custom.white",
      fontWeight: "400",
      fontSize: "12px",
    },
  },
  InrDropdown: {
    "@media(max-width:480px)": {
      "& #select-country-select-one": {
        paddingRight: "20px",
      },
    },
  },
  InrDropdownContainer: {
    maxWidth: "120px",
    marginLeft: "50px",
    "@media(max-width:480px)": {
      maxWidth: "120px",
      marginLeft: "20px",
    },
  },
  Inter16NormalBottomBorder: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    padding: "0 !important",
    color: "#FFFFFF",
    borderBottom: "1px dashed #FFF",
  },

  mobHeading: {
    "@media(max-width:480px)": {
      display: "flex",
      padding: "10px",
      fontFamily: "Inter",
      fontStyle: "normal",
      fontWeight: 700,
      fontSize: "16px",
      color: "custom.white",
    },
    "&span": {
      padding: "10px",
    },
  },
  breadCrumb: {
    fontSize: "16px",
    fontWeight: "400",
    color: "#FFF",
    top: "0px",
    display: "flex",
    padding: "20px",
    display: "block !important",
    maxWidth: "1280px !important",
    color: "rgba(255,255,255,0.7)",
    "& a": {
      color: "#E14084",
      textDecoration: "none",
    },
    "& div": {
      display: "flex",
    },
    "& h1": {
      fontSize: "18px",
      fontWeight: "600",
      cursor: "pointer",
      marginTop: "-3px",
      color: "custom.white",
    },
    "& img": {
      paddingRight: "10px",
      width: "40px",
      height: "20px",
      cursor: "pointer",
      mixBlendMode: "exclusion",
    },
    "@media(max-width:480px)": {
      fontSize: "14px",
      fontWeight: "400",
      color: "#fff",
      padding: "0 10px",
      display: "block",
    },
  },

  formGroup: {
    position: "relative",
    display: "block",
    width: "100%",
    marginBottom: "20px",
    width: "100%",
    maxWidth: "608px",
    marginLeft: "33px",
    // margin: "auto",
    fontSize: "16px",
    "@media(max-width:480px)": {
      marginLeft: "0px",
    },
  },
  inputField: {
    position: "relative",
    display: "block",
    width: "100%",
    fontSize: "14px",
    backgroundColor: "custom.marketPlaceBuyInput",
    height: "auto",
    color: "rgba(255, 255, 255, 0.75)",
    borderRadius: "12px",
    border: "solid",
    borderColor: "custom.marketPlaceBuyInputBorder",
    borderWidth: "thin",
    padding: "4px 15px",
    "& option": {
      color: "initial",
      fontWeight: "400",
    },
  },
  errorField: {
    border: "1px solid #E5392E",
  },

  promoCodeStyle: {
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "16px",
    lineHeight: "19px",
    textAlign: "left",
    color: "custom.white",
    marginBottom: "10px",
    marginTop: "20px",
  },
  promoBalance: {
    display: "flex",
    alignItems: "center",
    textAlign: "right",
    color: "custom.white",
    marginLeft: "18px",
  },
  msgOverflowScroll: {
    position: "relative",
    display: "block",
    width: "100%",
    maxWidth: "512px",
    background: "#fff",
    margin: "auto",
    padding: "40px 40px 10px 40px",
    borderRadius: "20px",
    top: "50%",
    transform: "translateY(-50%)",
    "& > div": {
      maxHeight: "450px",
      overflowY: "scroll",
      "&::-webkit-scrollbar": {
        display: "none",
      },
    },
    "@media(max-width:767px)": {
      width: "90%",
      padding: "15px",
    },
  },

  promoTitle: {
    fontStyle: "normal",
    fontWeight: "medium",
    fontSize: "16px",
    lineHeight: "30px",
    marginBottom: "10px",
    color: "#000000",
  },
  promoSaved: {
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "24px",
    lineHeight: "30px",
    marginBottom: "10px",
  },
  promoBottomText: {
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "16px",
    lineHeight: "30px",
    marginBottom: "10px",
    color: "#E14084",
  },
  Inter14Normal: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "14px",
    marginBottom: "10px",
  },
  appliedContainer: {
    padding: "10px",
    background: "#2A2C3B",
    opacity: "0.75",
    border: "1px solid #54B5BB",
    borderRadius: "16px",
    display: "flex",
    justifyContent: "space-between",
    color: "#54B5BB",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "19px",
    "& span": {
      fontWeight: 500,
      fontSize: "16px",
      lineHeight: "30px",
    },
  },

  tradableContainer: {
    color: "custom.white",
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "20px auto 10px",
    width: "100%",
    maxWidth: "608px",
    backgroundColor: "custom.tradableContainerBg",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "10px",
    width: "100%",
    "& li": {
      padding: "8px 0px 0px 0px",
      fontWeight: 500,
      lineHeight: "21px",
      fontSize: "14px",
    },
    "& ul": {
      paddingLeft: "22px",
      marginTop: "5px",
    },
  },
  infoText: {
    color: "#FFF",
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "30px auto 24px",
    width: "100%",
    maxWidth: "460px",
    borderRadius: "10px",
    width: "100%",
    textAlign: "center",
  },
  heading: {
    margin: "10px",
  },

  gradText: {
    background: "-webkit-linear-gradient(#B237F6,#E94177)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
};
export default style;
